import numpy as np
a = np.array([])
arr1 = np.arange(1, 5).reshape(2, 2)
print(arr1)
arr2 = np.arange(5, 9).reshape(2, 2)
print(arr2)
# b = np.append(, axis=1)
# print(b)
arr3 = np.append(arr1, arr2, axis=1)
print(arr3)